import type { AgentRecord, AgentRepository, IdempotencyRepository } from "@/server/domain";
import type { AgentWalletProvisioner } from "@/server/wallets/provisioner";
import { AppError } from "@/server/errors";
import { logEvent, logFailure } from "@/server/logger";
import { parseUsdcAmount, formatUsdcAmount } from "@/lib/usdc";
export interface CreateAgentInput {name:string;description:string;dailySpendLimit:string;singleTransactionLimit:string;approvalThreshold:string;idempotencyKey:string}
export type PublicAgent={id:string;name:string;description:string;walletAddress:`0x${string}`;blockchain:"ARC-TESTNET";accountType:"SCA"|"EOA";status:AgentRecord["status"];balance:string;dailySpendLimit:string;singleTransactionLimit:string;approvalThreshold:string;createdAt:string;updatedAt:string};
export const toPublicAgent=(a:AgentRecord):PublicAgent=>({id:a.id,name:a.name,description:a.description,walletAddress:a.walletAddress,blockchain:a.blockchain,accountType:a.accountType,status:a.status,balance:"0.00",dailySpendLimit:formatUsdcAmount(a.dailySpendLimit),singleTransactionLimit:formatUsdcAmount(a.singleTransactionLimit),approvalThreshold:formatUsdcAmount(a.approvalThreshold),createdAt:a.createdAt.toISOString(),updatedAt:a.updatedAt.toISOString()});
export class AgentService {constructor(private agents:AgentRepository,private requests:IdempotencyRepository,private wallets:AgentWalletProvisioner){}
 async createAuthenticated(ownerUserId:string|null,input:CreateAgentInput,walletSetId:string,requestId?:string){if(!ownerUserId)throw new AppError("UNAUTHENTICATED",401,"Connect and authenticate your owner wallet.");return this.create(ownerUserId,input,walletSetId,requestId)}
 async create(ownerUserId:string,input:CreateAgentInput,walletSetId:string,requestId:string=crypto.randomUUID()){const dailySpendLimit=parseUsdcAmount(input.dailySpendLimit);const singleTransactionLimit=parseUsdcAmount(input.singleTransactionLimit);const approvalThreshold=parseUsdcAmount(input.approvalThreshold);logEvent("agent.creation.requested",{requestId,userId:ownerUserId});const state=await this.requests.reserve(ownerUserId,input.idempotencyKey);if(state==="completed"){const id=await this.requests.getCompletedAgentId(ownerUserId,input.idempotencyKey);const existing=id?await this.agents.findByOwnerAndId(ownerUserId,id):null;if(existing)return existing;throw new AppError("IDEMPOTENCY_INCONSISTENT",500,"The previous request could not be recovered.")}if(state==="pending")throw new AppError("REQUEST_IN_PROGRESS",409,"An agent creation request with this key is already in progress.");let provisioned=false;const id=crypto.randomUUID();try{const wallet=await this.wallets.createWallet({walletSetId});provisioned=true;logEvent("agent.wallet.provisioned",{requestId,userId:ownerUserId,agentId:id});const now=new Date();const record:AgentRecord={id,ownerUserId,name:input.name,description:input.description,provider:"circle",providerWalletId:wallet.providerWalletId,walletAddress:wallet.walletAddress,blockchain:wallet.blockchain,accountType:wallet.accountType,status:"active",dailySpendLimit,singleTransactionLimit,approvalThreshold,createdAt:now,updatedAt:now};const saved=await this.agents.create(record);await this.requests.complete(ownerUserId,input.idempotencyKey,id);logEvent("agent.persisted",{requestId,userId:ownerUserId,agentId:id});return saved}catch(error){logFailure("agent.creation.failed",{requestId,userId:ownerUserId,agentId:id,stage:provisioned?"persistence":"provisioning"});if(provisioned)throw new AppError("AGENT_PERSISTENCE_FAILED",500,"The wallet was provisioned but its record could not be saved. Support intervention is required; do not retry.");throw new AppError("AGENT_PROVISIONING_AMBIGUOUS",502,"Wallet provisioning did not complete with a confirmed result. Do not retry this request; support reconciliation is required.")}}
 async list(owner:string){return this.agents.listByOwner(owner)} async get(owner:string,id:string){return this.agents.findByOwnerAndId(owner,id)} }
