import { describe, expect, it } from "vitest";
import { AgentService } from "./service";
import type { AgentRecord, AgentRepository, IdempotencyRepository } from "@/server/domain";
import type { AgentWalletProvisioner } from "@/server/wallets/provisioner";
class Agents implements AgentRepository {items:AgentRecord[]=[];fail=false;async create(a:AgentRecord){if(this.fail)throw new Error("db");this.items.push(a);return a}async listByOwner(o:string){return this.items.filter(a=>a.ownerUserId===o)}async findByOwnerAndId(o:string,id:string){return this.items.find(a=>a.ownerUserId===o&&a.id===id)??null}}
class Requests implements IdempotencyRepository {items=new Map<string,{status:string;id?:string}>();key(o:string,k:string){return `${o}:${k}`}async reserve(o:string,k:string){const v=this.items.get(this.key(o,k));if(v)return v.status as "pending"|"completed";this.items.set(this.key(o,k),{status:"pending"});return "reserved" as const}async complete(o:string,k:string,id:string){this.items.set(this.key(o,k),{status:"completed",id})}async getCompletedAgentId(o:string,k:string){return this.items.get(this.key(o,k))?.id??null}}
class Wallets implements AgentWalletProvisioner {calls=0;fail=false;async createWallet(){this.calls++;if(this.fail)throw new Error("provider");return {provider:"circle" as const,providerWalletId:"circle-1",walletAddress:"0x1234000000000000000000000000000000007890" as const,blockchain:"ARC-TESTNET" as const,accountType:"SCA" as const}}async getWallet(){return this.createWallet()}}
const input={name:"Research Agent",description:"Research",dailySpendLimit:"20",singleTransactionLimit:"10",approvalThreshold:"5",idempotencyKey:"11111111-1111-4111-8111-111111111111"};
describe("AgentService",()=>{it("rejects an unauthenticated request before provisioning",async()=>{const w=new Wallets();await expect(new AgentService(new Agents(),new Requests(),w).createAuthenticated(null,input,"set")).rejects.toMatchObject({code:"UNAUTHENTICATED"});expect(w.calls).toBe(0)});it("provisions and persists",async()=>{const a=new Agents(),w=new Wallets();const result=await new AgentService(a,new Requests(),w).create("user-a",input,"set");expect(result.ownerUserId).toBe("user-a");expect(w.calls).toBe(1);expect(a.items).toHaveLength(1)});it("preserves an ambiguous provider request without persistence",async()=>{const a=new Agents(),w=new Wallets(),r=new Requests();w.fail=true;await expect(new AgentService(a,r,w).create("user-a",input,"set")).rejects.toMatchObject({code:"AGENT_PROVISIONING_AMBIGUOUS"});expect(a.items).toHaveLength(0);expect(await r.reserve("user-a",input.idempotencyKey)).toBe("pending")});it("returns an idempotent result without a second wallet",async()=>{const a=new Agents(),w=new Wallets(),r=new Requests(),s=new AgentService(a,r,w);const first=await s.create("user-a",input,"set");const second=await s.create("user-a",input,"set");expect(second.id).toBe(first.id);expect(w.calls).toBe(1)});it("surfaces persistence failure and preserves pending reservation",async()=>{const a=new Agents(),w=new Wallets(),r=new Requests();a.fail=true;await expect(new AgentService(a,r,w).create("user-a",input,"set")).rejects.toMatchObject({code:"AGENT_PERSISTENCE_FAILED"});expect(w.calls).toBe(1);expect(await r.reserve("user-a",input.idempotencyKey)).toBe("pending")});it("enforces owner-scoped reads",async()=>{const a=new Agents(),s=new AgentService(a,new Requests(),new Wallets());const created=await s.create("user-a",input,"set");await expect(s.get("user-b",created.id)).resolves.toBeNull()})});
