"use client";
import { useState } from "react";
import { Copy, ExternalLink, LockKeyhole } from "lucide-react";
import { useAccount, useSignMessage } from "wagmi";
import { authenticateOwner } from "@/features/auth/authenticate";
import type { PublicAgent } from "./public-agent";
import { Panel, Status } from "@/components/ui";
export function AgentDetail({agentId}:{agentId:string}){const {address}=useAccount();const {signMessageAsync}=useSignMessage();const [agent,setAgent]=useState<PublicAgent|null>(null);const [loadedOwner,setLoadedOwner]=useState<string|null>(null);const [error,setError]=useState("");const [loading,setLoading]=useState(false);async function load(){if(!address)return;try{setLoading(true);setError("");await authenticateOwner({address,signMessage:m=>signMessageAsync({message:m})});const response=await fetch(`/api/agents/${encodeURIComponent(agentId)}`);const value=await response.json();if(!response.ok)throw new Error(value.error?.message??"Agent not found.");setAgent(value.data.agent);setLoadedOwner(address)}catch(e){setError(e instanceof Error?e.message:"Could not load agent.")}finally{setLoading(false)}}
 if(!agent||loadedOwner?.toLowerCase()!==address?.toLowerCase())return <Panel><LockKeyhole className="text-acid"/><h2 className="mt-5">Owner authentication required</h2><p className="mt-3 text-sm text-muted">Only the wallet that owns this agent can retrieve its metadata.</p>{error&&<p className="mt-4 text-sm text-red-300">{error}</p>}<button className="button mt-5" disabled={!address||loading} onClick={load}>{loading?"Authenticating…":address?"Authenticate & open":"Connect wallet first"}</button></Panel>;
 return <><div className="flex flex-wrap items-start justify-between gap-4"><div><div className="eyebrow">Circle-backed agent wallet</div><h1 className="mt-2 text-3xl">{agent.name}</h1><p className="mt-2 text-sm text-muted">{agent.description}</p></div><Status tone="ok">{agent.status}</Status></div><div className="mt-8 grid gap-px border border-line bg-line sm:grid-cols-2 lg:grid-cols-4">{[["Balance","0.00 USDC"],["Network","ARC TESTNET"],["Account type",agent.accountType],["Asset","USDC"]].map(([l,v])=><div className="bg-panel p-5" key={l}><div className="label">{l}</div><div className="font-mono">{v}</div></div>)}</div><Panel className="mt-6"><div className="label">Arc wallet address</div><code className="break-all text-sm">{agent.walletAddress}</code><div className="mt-5 flex flex-wrap gap-3"><button className="button button-secondary" onClick={()=>navigator.clipboard.writeText(agent.walletAddress)}><Copy size={14}/>Copy</button><a className="button button-secondary" target="_blank" rel="noreferrer" href={`https://testnet.arcscan.app/address/${agent.walletAddress}`}><ExternalLink size={14}/>Explorer</a></div></Panel><div className="mt-6 grid gap-4 lg:grid-cols-2"><Panel><h2>Spending policy</h2><dl className="mt-5 space-y-4 text-sm">{[["Daily limit",`${agent.dailySpendLimit} USDC`],["Transaction limit",`${agent.singleTransactionLimit} USDC`],["Approval threshold",`${agent.approvalThreshold} USDC`]].map(([l,v])=><div className="flex justify-between border-b border-line pb-3" key={l}><dt className="text-muted">{l}</dt><dd className="font-mono">{v}</dd></div>)}</dl></Panel><Panel><h2>Recent activity</h2><p className="mt-5 text-sm text-muted">No persisted activity yet. Wallet provisioning is the only Phase 2 lifecycle action.</p></Panel></div><div className="mt-6 flex flex-wrap gap-3"><button className="button button-secondary" disabled>Fund agent · Phase 3</button><button className="button button-secondary" disabled>Pause agent · Not implemented</button><button className="button button-secondary" disabled>Edit policy · Not implemented</button></div></>}
