"use client";
import Link from "next/link";
import { useRef, useState, type FormEvent } from "react";
import { CheckCircle2, Copy, ExternalLink } from "lucide-react";
import { useAccount, useSignMessage, useSwitchChain } from "wagmi";
import { authenticateOwner } from "@/features/auth/authenticate";
import type { PublicAgent } from "./public-agent";
import { ARC_TESTNET_CHAIN_ID } from "@/config/arc";
type Phase="idle"|"authenticating"|"provisioning"|"success"|"error"|"blocked";
class RequestError extends Error {constructor(message:string,public code?:string){super(message)}}
export function CreateAgentForm(){const {address,isConnected,chainId}=useAccount();const {signMessageAsync}=useSignMessage();const {switchChain,isPending:switching}=useSwitchChain();const [phase,setPhase]=useState<Phase>("idle");const [agent,setAgent]=useState<PublicAgent|null>(null);const [error,setError]=useState("");const submitting=useRef(false);const idempotencyKey=useRef<string|null>(null);const wrongChain=isConnected&&chainId!==ARC_TESTNET_CHAIN_ID;
 async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();if(submitting.current||wrongChain)return;if(!address){setError("Connect an owner wallet before creating an agent.");setPhase("error");return}submitting.current=true;idempotencyKey.current??=crypto.randomUUID();const data=new FormData(event.currentTarget);try{setError("");setPhase("authenticating");await authenticateOwner({address,signMessage:(message)=>signMessageAsync({message})});setPhase("provisioning");const response=await fetch("/api/agents",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({name:data.get("name"),description:data.get("description"),dailySpendLimit:data.get("daily"),singleTransactionLimit:data.get("single"),approvalThreshold:data.get("approval"),idempotencyKey:idempotencyKey.current})});const value=await response.json();if(!response.ok)throw new RequestError(value.error?.message??"Agent creation failed.",value.error?.code);setAgent(value.data.agent);setPhase("success")}catch(cause){setError(cause instanceof Error?cause.message:"Agent creation failed.");const unsafe=cause instanceof RequestError&&["AGENT_PROVISIONING_AMBIGUOUS","AGENT_PERSISTENCE_FAILED","REQUEST_IN_PROGRESS"].includes(cause.code??"");setPhase(unsafe?"blocked":"error")}finally{submitting.current=false}}
 if(phase==="success"&&agent)return <section className="panel max-w-3xl"><CheckCircle2 className="text-acid"/><div className="eyebrow mt-6">Agent online</div><h2 className="mt-2 text-2xl">{agent.name}</h2><div className="mt-6 grid gap-5 border-y border-line py-5 sm:grid-cols-3"><div><span className="label">Network</span>ARC TESTNET</div><div><span className="label">Asset / Balance</span>USDC · 0.00</div><div><span className="label">Status</span>ACTIVE</div></div><div className="mt-5"><span className="label">Wallet</span><code className="break-all text-sm">{agent.walletAddress}</code></div><div className="mt-6 flex flex-wrap gap-3"><button className="button button-secondary" onClick={()=>navigator.clipboard.writeText(agent.walletAddress)}><Copy size={14}/>Copy address</button><a className="button button-secondary" target="_blank" rel="noreferrer" href={`https://testnet.arcscan.app/address/${agent.walletAddress}`}><ExternalLink size={14}/>View on explorer</a><Link className="button" href={`/app/agents/${agent.id}`}>Open agent</Link></div><p className="mt-5 text-xs text-muted">Wallet provisioned on Arc Testnet. It is not funded and no transaction was submitted.</p></section>;
 return <form className="panel max-w-3xl" onSubmit={submit}><div className="grid gap-5 sm:grid-cols-2"><label className="sm:col-span-2"><span className="label">Agent name</span><input className="input" name="name" required minLength={2} maxLength={60}/></label><label className="sm:col-span-2"><span className="label">Description</span><textarea className="input min-h-24" name="description" required maxLength={240}/></label>{[["Daily spending limit","daily"],["Single transaction limit","single"],["Approval threshold","approval"]].map(([label,name])=><label key={name}><span className="label">{label} · USDC</span><input className="input" name={name} type="text" required inputMode="decimal" pattern="^(0|[1-9][0-9]*)(\.[0-9]{1,6})?$"/></label>)}<div><span className="label">Asset</span><div className="input text-muted">USDC · Fixed</div></div><div><span className="label">Network</span><div className="input text-muted">Arc Testnet · Fixed</div></div></div>{!isConnected&&<div className="mt-5 border border-line p-3 text-sm text-muted">Connect your owner wallet from the console header to create an agent.</div>}{wrongChain&&<div className="mt-5 border border-amber-800 bg-amber-950/30 p-3 text-sm text-amber-300">Agent wallets are Arc-only. Switch your owner wallet to Arc Testnet before authenticating.</div>}{error&&<div className="mt-5 border border-red-900 bg-red-950/30 p-3 text-sm text-red-300">{error}{phase==="blocked"&&<span className="mt-2 block text-xs">Retry is disabled because the prior provisioning result is ambiguous. Contact support for reconciliation.</span>}</div>}<div className="mt-6 border-t border-line pt-6">{wrongChain?<button type="button" className="button" disabled={switching} onClick={()=>switchChain({chainId:ARC_TESTNET_CHAIN_ID})}>{switching?"Switching…":"Switch to Arc Testnet"}</button>:<button className="button" disabled={!isConnected||phase==="authenticating"||phase==="provisioning"||phase==="blocked"}>{phase==="authenticating"?"Authenticating owner…":phase==="provisioning"?"Provisioning Arc wallet…":"Create agent"}</button>}<p className="mt-3 text-xs text-muted">Your connected wallet signs a short-lived challenge. Circle credentials and signing infrastructure remain server-side.</p></div></form>}
