"use client";
import { useState } from "react";
import Link from "next/link";
import { useAccount, useSignMessage } from "wagmi";
import { authenticateOwner } from "@/features/auth/authenticate";
import type { PublicAgent } from "./public-agent";
import { Status } from "@/components/ui";
export function RealAgentList(){const {address}=useAccount();const {signMessageAsync}=useSignMessage();const [agents,setAgents]=useState<PublicAgent[]|null>(null);const [loadedOwner,setLoadedOwner]=useState<string|null>(null);const [error,setError]=useState("");const [loading,setLoading]=useState(false);async function load(){if(!address)return;try{setLoading(true);setError("");await authenticateOwner({address,signMessage:m=>signMessageAsync({message:m})});const response=await fetch("/api/agents");const value=await response.json();if(!response.ok)throw new Error(value.error?.message??"Could not load agents.");setAgents(value.data.agents as PublicAgent[]);setLoadedOwner(address)}catch(e){setError(e instanceof Error?e.message:"Could not load agents.")}finally{setLoading(false)}}
 if(!agents||loadedOwner?.toLowerCase()!==address?.toLowerCase())return <div className="panel"><h2>Authenticated agent registry</h2><p className="mt-3 text-sm text-muted">Sign a short-lived challenge to load only the agents owned by your connected wallet.</p>{error&&<p className="mt-4 text-sm text-red-300">{error}</p>}<button className="button mt-5" disabled={!address||loading} onClick={load}>{loading?"Authenticating…":address?"Authenticate & load":"Connect wallet first"}</button></div>;
 if(agents.length===0)return <div className="panel"><p className="text-muted">No persisted agent wallets belong to this owner.</p><Link href="/app/agents/new" className="button mt-5">Create first agent</Link></div>;
 return <div className="grid gap-4 lg:grid-cols-2">{agents.map((agent:PublicAgent)=><Link href={`/app/agents/${agent.id}`} className="panel transition hover:border-acid" key={agent.id}><div className="flex justify-between"><h2>{agent.name}</h2><Status tone="ok">{agent.status}</Status></div><p className="mt-2 text-sm text-muted">{agent.description}</p><div className="mt-6 font-mono text-lg">0.00 <small className="text-xs text-muted">USDC</small></div><code className="mt-4 block text-xs text-muted">{agent.walletAddress.slice(0,10)}…{agent.walletAddress.slice(-8)}</code></Link>)}</div>}
