import Link from "next/link";
import { Activity, Bot, Gauge, ListChecks, ShieldCheck } from "lucide-react";
import type { ReactNode } from "react";
import { Logo } from "./logo";
import { WalletControl } from "@/features/wallet/wallet-control";
const links = [{ href: "/app", label: "Control center", icon: Gauge }, { href: "/app/agents", label: "Agents", icon: Bot }, { href: "/app/policies", label: "Policies", icon: ShieldCheck }, { href: "/app/approvals", label: "Approvals", icon: ListChecks }, { href: "/app/activity", label: "Activity", icon: Activity }];
export function AppShell({ children }: { children: ReactNode }) { return <div className="min-h-screen md:grid md:grid-cols-[248px_1fr]">
  <aside className="border-b border-white/[.07] bg-[#090d10]/90 backdrop-blur-xl md:sticky md:top-0 md:h-screen md:border-b-0 md:border-r"><div className="border-b border-white/[.06] p-5"><Logo /><div className="mt-4 flex items-center gap-2 font-mono text-[9px] uppercase tracking-[.18em] text-muted"><span className="h-1.5 w-1.5 rounded-full bg-acid shadow-[0_0_10px_rgba(149,245,195,.65)]"/>Arc control plane</div></div><nav className="flex overflow-x-auto px-3 py-3 md:block md:px-3 md:py-5">{links.map(({href,label,icon:Icon}) => <Link key={href} href={href} className="nav-link"><span className="grid h-8 w-8 place-items-center rounded-md border border-white/[.06] bg-white/[.025]"><Icon size={15}/></span>{label}</Link>)}</nav><div className="hidden absolute bottom-0 left-0 right-0 border-t border-white/[.06] bg-black/10 p-5 text-[10px] leading-5 text-muted md:block"><span className="font-mono tracking-[.14em] text-white/60">PHASE 1 · PROTOTYPE</span><br/>No funds are executed.</div></aside>
  <div className="min-w-0"><header className="sticky top-0 z-20 flex min-h-16 items-center justify-between border-b border-white/[.07] bg-[#070a0c]/75 px-5 backdrop-blur-2xl lg:px-8"><span className="font-mono text-[10px] tracking-[.22em] text-muted">ARC CONTROL PLANE</span><WalletControl /></header><main className="mx-auto w-full max-w-[1500px] p-5 lg:p-8 xl:p-10">{children}</main></div>
</div>; }
